//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1026.
// 
#pragma warning disable 1591

namespace Cliente.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoSoap", Namespace="http://tempuri.org/")]
    public partial class Servico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadArquivoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servico() {
            this.Url = global::Cliente.Properties.Settings.Default.Cliente_localhost_Servico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadArquivoCompletedEventHandler UploadArquivoCompleted;
        
        /// <remarks/>
        public event DownloadArquivoCompletedEventHandler DownloadArquivoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadArquivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadArquivo(string nomeDoArquivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] arquivoByte) {
            object[] results = this.Invoke("UploadArquivo", new object[] {
                        nomeDoArquivo,
                        arquivoByte});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadArquivoAsync(string nomeDoArquivo, byte[] arquivoByte) {
            this.UploadArquivoAsync(nomeDoArquivo, arquivoByte, null);
        }
        
        /// <remarks/>
        public void UploadArquivoAsync(string nomeDoArquivo, byte[] arquivoByte, object userState) {
            if ((this.UploadArquivoOperationCompleted == null)) {
                this.UploadArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadArquivoOperationCompleted);
            }
            this.InvokeAsync("UploadArquivo", new object[] {
                        nomeDoArquivo,
                        arquivoByte}, this.UploadArquivoOperationCompleted, userState);
        }
        
        private void OnUploadArquivoOperationCompleted(object arg) {
            if ((this.UploadArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadArquivoCompleted(this, new UploadArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadArquivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadArquivo(string nomeDoArquivo) {
            object[] results = this.Invoke("DownloadArquivo", new object[] {
                        nomeDoArquivo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DownloadArquivoAsync(string nomeDoArquivo) {
            this.DownloadArquivoAsync(nomeDoArquivo, null);
        }
        
        /// <remarks/>
        public void DownloadArquivoAsync(string nomeDoArquivo, object userState) {
            if ((this.DownloadArquivoOperationCompleted == null)) {
                this.DownloadArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadArquivoOperationCompleted);
            }
            this.InvokeAsync("DownloadArquivo", new object[] {
                        nomeDoArquivo}, this.DownloadArquivoOperationCompleted, userState);
        }
        
        private void OnDownloadArquivoOperationCompleted(object arg) {
            if ((this.DownloadArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadArquivoCompleted(this, new DownloadArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UploadArquivoCompletedEventHandler(object sender, UploadArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DownloadArquivoCompletedEventHandler(object sender, DownloadArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591